// Thẻ cữ thuốc — dùng chung bởi DashboardView và ScheduleView.
import type { ScheduledDoseRow } from "../../../types";
import Icon from "./Icon";
import { doseStatus, isDoseLocked, prettyTime, type DoseAction } from "./utils";

function formatDoseValue(value: ScheduledDoseRow["dose_value"]) { if (value === null || value === undefined || value === "") return ""; const num = Number(value); return Number.isFinite(num) ? String(num) : String(value); }

export function doseLabel(dose: ScheduledDoseRow) { return [dose.dose_value && `${formatDoseValue(dose.dose_value)} ${dose.dose_unit ?? ""}`, dose.meal_relation].filter(Boolean).join(" · ") || "Dùng theo đơn đã duyệt"; }

export function NextDose({ dose, busy, onAction }: { dose: ScheduledDoseRow; busy: boolean; onAction: DoseAction }) { const locked = isDoseLocked(dose); return <div className={`next-dose ${locked ? "locked" : ""}`}><div className="next-dose-main"><span className="medicine-bubble"><Icon name="pill" size={25}/></span><div><span className="next-time"><Icon name="clock" size={17}/> {prettyTime(dose.current_scheduled_at)}</span><h2>{dose.medication_name}</h2><p>{doseLabel(dose)}</p></div></div>{locked ? <div className="dose-locked-note"><Icon name="clock" size={16}/> Có thể xác nhận khi đến giờ uống</div> : <DoseActions dose={dose} busy={busy} onAction={onAction}/>}</div>; }

export default function DoseCard({ dose, busy, onAction }: { dose: ScheduledDoseRow; busy: boolean; onAction: DoseAction }) { const locked = isDoseLocked(dose); const [label, status] = locked ? ["Chưa đến giờ", "locked"] as const : doseStatus(dose.status); return <article className={`patient-dose ${status}`}><div className="dose-time">{prettyTime(dose.current_scheduled_at)}</div><div className="dose-info"><span className="mini-pill"><Icon name="pill" size={17}/></span><div><h3>{dose.medication_name}</h3><p>{doseLabel(dose)}</p></div></div><span className={`dose-status ${status}`}>{label}</span>{!locked && (status === "upcoming" || status === "late") ? <DoseActions dose={dose} busy={busy} compact onAction={onAction}/> : <span className={`dose-done-mark ${locked ? "locked" : ""}`}><Icon name={locked ? "clock" : "check"} size={18}/></span>}</article>; }

export function DoseActions({ dose, busy, compact = false, onAction }: { dose: ScheduledDoseRow; busy: boolean; compact?: boolean; onAction: DoseAction }) { return <div className={compact ? "dose-actions compact" : "dose-actions"}><button className="take" disabled={busy} onClick={() => void onAction(dose, "TAKEN")}><Icon name="check" size={16}/>{busy ? "Đang lưu…" : "Đã uống"}</button><button disabled={busy} onClick={() => void onAction(dose, "SNOOZE")}><Icon name="clock" size={15}/> Nhắc sau</button><button className="skip" disabled={busy} onClick={() => void onAction(dose, "SKIPPED")}>Bỏ qua</button></div>; }
