import { useEffect, useState } from "react";

import { ApiError, api } from "../../../api";
import Icon from "./Icon";

export default function SosView({ patientId, onDone }: { patientId: string; onDone: (message: string) => void }) {
  const [holding, setHolding] = useState(false), [sent, setSent] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!holding || busy || sent) return; const timer = window.setTimeout(async () => { setBusy(true); try { await api.triggerSos(patientId); setSent(true); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Không gửi được cảnh báo SOS"); } finally { setBusy(false); setHolding(false); } }, 3000); return () => window.clearTimeout(timer); }, [holding, busy, patientId, sent]);
  return <section className="sos-page"><div className="sos-info-panel"><span className="sos-shield"><Icon name="shield" size={28}/></span><h2>Hỗ trợ khẩn cấp</h2><p>Giữ nút SOS trong 3 giây. Hệ thống sẽ gửi cảnh báo tới đội ngũ chăm sóc và bác sĩ phụ trách.</p><ul><li><Icon name="check" size={17}/> Ghi nhận cảnh báo trên hệ thống</li><li><Icon name="check" size={17}/> Thông báo tới bác sĩ phụ trách</li><li><Icon name="check" size={17}/> Theo dõi trạng thái xử lý</li></ul><div className="sos-disclaimer"><Icon name="alert" size={18}/><span><b>Trong tình huống nguy hiểm tính mạng</b>Hãy gọi ngay số cấp cứu 115. SOS trong ứng dụng không thay thế dịch vụ cấp cứu.</span></div></div><div className="sos-action-panel"><button className={`sos-button ${holding ? "holding" : ""}`} disabled={busy || sent} onPointerDown={() => setHolding(true)} onPointerUp={() => setHolding(false)} onPointerLeave={() => setHolding(false)} onPointerCancel={() => setHolding(false)}><span>{sent ? "ĐÃ GỬI" : busy ? "ĐANG GỬI" : "SOS"}</span><small>{sent ? "CẢNH BÁO SOS" : "GIỮ 3 GIÂY ĐỂ GỬI"}</small></button><h1>{sent ? "Cảnh báo đã được ghi nhận" : "Bạn cần trợ giúp?"}</h1><p>{sent ? "Hệ thống đã ghi nhận cảnh báo và đang chuyển tới đội ngũ chăm sóc." : "Nhấn giữ nút phía trên để xác nhận gửi cảnh báo."}</p>{error && <b className="sos-error">{error}</b>}<button className="sos-cancel" onClick={() => onDone(sent ? "Đã đóng cảnh báo SOS" : "")}>{sent ? "Quay về tổng quan" : "Huỷ và quay lại"}</button></div></section>;
}
